export const BASE_URL = "http://localhost:3001/api/";
// export const BASE_PLATAFORMS = BASE_URL + "platforms/plataforms";
export const CHARACTERS_URL = BASE_URL + "character/character";
export const EPISODE_URL = BASE_URL + "episode/episode/";
export const LOCATION_URL = BASE_URL + "location/location/";
export const CHARACTERSID_URL = BASE_URL + "character/character/";
// export const VIDEOGAME_CREATE_URL = BASE_URL + "videogames/videogame";
// export const GENRES_URL = BASE_URL + "genres/genres";
// export const IMAGES_URL = BASE_URL + "image";
